"""Create Admin table

Revision ID: 417d039ade4f
Revises: 4812cd285b75
Create Date: 2026-07-31 13:27:24.801446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '417d039ade4f'
down_revision = '4812cd285b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('admins_admin_code_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('admins_email_key'), type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('is_super_admin')
        batch_op.drop_column('full_name')
        batch_op.drop_column('admin_code')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('admins_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('admins_admin_code_key'), ['admin_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
