"""Initial database schema

Revision ID: 78aa1efdece9
Revises: 680f588b6d16
Create Date: 2026-07-31 19:30:33.338509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aa1efdece9'
down_revision = '680f588b6d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_charge', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_order_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gateway_payment_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gateway_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['order_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trending', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_best_seller', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('brand')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_product_review', ['user_id', 'product_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_product_wishlist', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_product_wishlist', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_product_review', type_='unique')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_best_seller')
        batch_op.drop_column('is_trending')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('discount_price')
        batch_op.drop_column('sku')
        batch_op.drop_column('slug')
        batch_op.drop_column('brand_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('currency')
        batch_op.drop_column('gateway_signature')
        batch_op.drop_column('gateway_payment_id')
        batch_op.drop_column('gateway_order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('shipping_charge')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('price')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    op.drop_table('brands')
    # ### end Alembic commands ###
